### PR TITLE
shorten command names

### LINKED ISSUE #1: Redundant command names
The `addrole`, `deleterole`, and `removerole` commands are a bit redundant in their naming given that they must be prefixed by `rolebot`.

They should be shortened to `add`, `delete`, and `remove`. The `help` command verbiage should then be updated accordingly.

### PR DESCRIPTION
**Pull request by reevest2**
https://github.com/christopherplummer/RoleBot/issues/1

Need to update the GitHub Readme to reflect new command names for addrole, deleterole, removerole 
[should be add, delete, remove now].

### CODE REVIEW

**Review by StevenGarberg — APPROVED** [review]
Looks good. Only suggestion would be to update the class and file names for the 3 role commands, but that's more of a bonus.

**Comment by StevenGarberg** [comment]
@reevest2 When you do merge this in, please `Squash and merge` instead of `Merge pull request`, then delete your branch.

@christopherplummer we should probably figure out a way to force this as a policy for our repos. I think we can do it at an organizational level for the group you just made. Now we just have to figure out how to transfer ownership of all these open source repos to that.

**Comment by christopherplummer** [comment]
> 

Repo settings updated to only allow squash and merge.

**Review by christopherplummer — APPROVED** [review]

**Comment by StevenGarberg** [comment]
@christopherplummer Did you enable auto delete upon merge?

**Comment by reevest2** [comment]
Done @StevenGarberg

**Pull request merged**
